# server port configuration
server:
  port: 8083

# eureka server configuration
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

# spring application name
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**